### PR TITLE
implement support for fetching rows chunk by chunk

### PR DESCRIPTION
**Pull request by ebaudrez**
Hi kmx,

Hope you are doing well.

Your implementation fetches all of the rows matching an SQL SELECT in memory at once. No criticism - it does that very well :) However, my own binning & histogramming software (PDL::NDBin) has support for piecewise processing (e.g., calculates standard deviation for a pdl while keeping only a subset of the rows in memory at any given moment). So, while your software works fine with mine, I would have slightly faster performance and much lower memory usage if I could fetch data from the DB chunk by chunk (by avoiding the reallocations). (I work with satellite data and hundreds of millions of rows is not an exception.)

So I went ahead and implemented support for that (look for recycle_sth). Tell me what you think of it. I haven't implemented it for rdbi2D, partly because I didn't need it, and because I don't know if it makes much sense? Also, please tell me if something else is missing. I aimed to make a complete pull request with tests and documentation, but I might have overlooked something.

Best regards and thanks for the work, I like this module!
Edward

### CODE REVIEW

**Comment by ebaudrez** [comment]
Hi kmx, have you already had an opportunity to look at my contribution?

**Comment by kmx** [comment]
I have already noted somewhere (but cannot find it in github interface) that to me it would sound better to use `reuse_sth` or `keep_sth` instead of `recycle_sth` but I am not native English speaker :)

**Comment by kmx** [comment]
Another improvement: `rdbi1D` function should set `$$recycle_sth` to `undef` once there are no more rows to fetch.

Then it might look like:

``` perl
 my $N = 500_000;
 my $cached_sth;
 do {
   my ($values) = rdbi1D($dbh, "SELECT value FROM table", {recycle_sth => \$cached_sth, fetch_chunk => $N});
   # process $values
 } while (defined $cached_sth);
```

**Comment by kmx** [comment]
And looking at you example in doc we might also avoid necessity of setting `reshape_inc => $N` because if `recycle_sth` is set it makes sense to force `reshape_inc` to be the same value as `fetch_chunk` (unless the user explicitly sets something different).

**Comment by kmx** [comment]
And perhaps it is also a good idea to make `fetch_chunk` mandatory parameter once you use `recycle_sth` so that this piece:

``` perl
rdbi1D($dbh, $sql, {recycle_sth => \$cached_sth});
```

would croak saying `You need to explicitly specify 'fetch_chunk' when using 'recycle_sth'`

**Comment by ebaudrez** [comment]
Hi kmx, thanks for the suggestions. I've modified the code to take into account your first suggestion (refactoring the if statement). I don't know about declaring $sth a state variable - I'm not particularly bothered by the way you have to call rdbi1D with a recycled statement handle. I'll let you decide.

As to whether it should be called 'recycle_sth' or 'reuse_sth' or something else, I'm open to any suggestion. I thought 'recycle'ing was precisely what was happening, but I'm not a native speaker either. I recall naming it reuse_sth first and then renaming it to recycle_sth, but I can't seem to remember why I did that. I'll leave it up to you to decide.

The remaining suggestions I have yet to tackle when I have some time to work on this again. Will get back to you.

**Comment by ebaudrez** [comment]
Hi kmx

I've pushed some more commits. Now the statement handle pointed to by `recycle_sth` is set to `undef` when there are no more rows to fetch. As you will see in the example, I didn't recommend the `do ... while` logic that you suggested:

```
my $sth;
do {
  my ($values) = rdbi1D(..., {recycle_sth => \$sth});
  if ($values->nelem > 0) {
    # process values
  }
} while (defined $sth);
```

`rdbi1D()` may return an empty chunk if the number of rows happens to be an exact multiple of `fetch_chunk`. I find the code above to be slightly more verbose than necessary, so I opted to recommend this instead:

```
my $sth;
while (1) {
  my ($values) = rdbi1D(..., {recycle_sth => \$sth});
  last unless $sth;
  # process values
}
```

Is this acceptable for you? (I am also somewhat uncomfortable recommending `do { ... } while` in the documentation because it is not a "real" loop statement in Perl, as you are no doubt aware.) I thought this was just as legible. But of course, if you take care to avoid operating on empty piddles, `do { ... } while` will work as well. What is your opinion?

`reshape_inc` is now set to `fetch_chunk` by default, unless the user wants something else, as you suggested.

I have not made `fetch_chunk` a mandatory parameter, because I didn't really see a reason to require it. In my use cases, it doesn't really matter what the chunk size is, even though I would probably set it to something higher than 8000 for performance. Your thoughts?

Best regards
Edward

**Comment by kmx** [comment]
Hi, your last version seems fine to me.

One thing is the name `recycle_sth` vs. `reuse_sth` (which I like a bit more) but we can handle this later :)

Other thing that might be improved is detection of `$sth` with no more data - what about https://metacpan.org/pod/DBI#Active ? I have not tested it but it should be available as `$recycle_sth->{Active}` I guess.

So something like:

```
if ($recycle_sth) {
  if ($processed == 0 || !$recycle_sth->{Active}) {
    # signal to callers that all chunks have been fetched
    $$recycle_sth = undef;
  }
}
else {
  warn "rdbi1D: no data\n" if $processed == 0;
}
```

**Comment by ebaudrez** [comment]
Hi, kmx, thank you for the suggestion. I have finally found some time to look into this.

I tried the code you suggested, but unfortunately, it didn't turn out to work well during testing. The problem with the code you suggested is that `$sth->{Active}` may become unset while there are still rows to process (a partial chunk, i.e., the last one). This precludes the use of the following (IMHO elegant) `while` loop:

```
my $sth;
while (1) {
  my ($values) = rdbi1D(..., {recycle_sth => \$sth});
  last unless $sth;
  # process values
}
```

because `$sth` will be `undef` if the last chunk is incomplete (`$processed < $fetch_chunk` but not zero), and the last chunk won't be processed by the above loop. Relying on `$sth->{Active}` alone, and moving `last unless $sth` to the end of the loop as an alternative, raises the problem that the last chunk may be entirely empty (if the number of rows happens to be an exact multiple of the chunk size). Some of the code after `# process values` may not like empty piddles.

Of course it's possible to work around all of this, but I doubt whether either the interface or the implementation would benefit from it. Rather, I'm afraid it would be at the expense of clarity or simplicity.

What are your thoughts? Regarding `reuse_sth` vs. `recycle_sth`, I'm impartial. Tell me what you want, and I'll implement it :-)

**Comment by kmx** [comment]
OK, I withdraw my `$sth->{Active}` idea.

Please rename the parameter to `reuse_sth` and let's release it.

Thanks

**Comment by ebaudrez** [comment]
Done. Let me know if there is anything else I can do.

Regards

**Comment by kmx** [comment]
PDL-IO-DBI-0.010 released

Thanks for your time.

**Pull request merged**
